# Generated by Django 6.0.4 on 2026-05-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='supervisor_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='supervisor_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
